#ifndef EUI_KEYS_H
#define EUI_KEYS_H

/*
 * LoRaWAN identifiers/keys
 *
 * Keep these isolated from application logic so they are easy to rotate and
 * audit. This header is intentionally simple: it only defines the macros
 * consumed by the LoRaWAN join code.
 *
 * NOTE: Consider keeping this file out of version control for real products.
 */
/* BEGIN GENERATED BY gen_euis.py (do not edit by hand) */
/* QUIRETECH_ENG_TEST_UNIT */
#define LORAWAN_DEV_EUI                                                        \
  { 0x6b, 0x1b, 0x0d, 0xe1, 0x24, 0xa3, 0x92, 0x77 }

#define LORAWAN_JOIN_EUI                                                       \
  { 0x1e, 0x8d, 0x35, 0x89, 0x85, 0x80, 0x5a, 0x36 }

#define LORAWAN_APP_KEY                                                        \
  {                                                                            \
    0x09, 0x02, 0x75, 0xa0, 0x30, 0x1b, 0x62, 0xa0,    \
        0x24, 0x7b, 0xf9, 0x7d, 0xd6, 0xeb, 0xc1, 0x57                                                 \
  }
// /* DemoUnit_KraftHeinz */
// #define LORAWAN_DEV_EUI                                                        \
//   { 0x87, 0x1c, 0x79, 0xa2, 0x8d, 0xbd, 0x4f, 0x20 }

// #define LORAWAN_JOIN_EUI                                                       \
//   { 0xca, 0x3c, 0xe2, 0x73, 0x15, 0xc0, 0x54, 0xaa }

// #define LORAWAN_APP_KEY                                                        \
//   {                                                                            \
//     0xda, 0xd6, 0xe8, 0x7f, 0x26, 0xf1, 0x33, 0x14,    \
//         0xbd, 0xca, 0x14, 0xad, 0x57, 0x63, 0xb7, 0x0e                                                 \
//   }
/* END GENERATED BY gen_euis.py */
/*
 * Alternative key sets (kept here for convenience; comment/uncomment as needed)
 *
 * #define LORAWAN_DEV_EUI  { ... }
 * #define LORAWAN_JOIN_EUI { ... }
 * #define LORAWAN_APP_KEY  { ... }
 */

#endif /* EUI_KEYS_H */
