#ifndef EUI_KEYS_H
#define EUI_KEYS_H

/*
 * LoRaWAN identifiers/keys
 *
 * Keep these isolated from application logic so they are easy to rotate and
 * audit. This header is intentionally simple: it only defines the macros
 * consumed by the LoRaWAN join code.
 *
 * NOTE: Consider keeping this file out of version control for real products.
 */

/* BEGIN GENERATED BY gen_euis.py (do not edit by hand) */
#define LORAWAN_DEV_EUI                                                        \
  { 0x46, 0x4c, 0x58, 0xf4, 0x10, 0xce, 0x15, 0x43 }

#define LORAWAN_JOIN_EUI                                                        \
  { 0xda, 0xa8, 0x0c, 0x34, 0xea, 0xa1, 0x81, 0xad }

#define LORAWAN_APP_KEY                                                        \
  {                                                                            \
    0x75, 0xf4, 0xa1, 0xfb, 0xc0, 0x2c, 0x2b, 0x5b, 0x82, 0x77, 0x09, 0x1f,    \
        0x62, 0xbf, 0x03, 0x6f                                                 \
  }
/* END GENERATED BY gen_euis.py */
/*
 * Alternative key sets (kept here for convenience; comment/uncomment as needed)
 *
 * #define LORAWAN_DEV_EUI  { ... }
 * #define LORAWAN_JOIN_EUI { ... }
 * #define LORAWAN_APP_KEY  { ... }
 */

#endif /* EUI_KEYS_H */
