#ifndef EUI_KEYS_H
#define EUI_KEYS_H

/*
 * LoRaWAN identifiers/keys
 *
 * Keep these isolated from application logic so they are easy to rotate and
 * audit. This header is intentionally simple: it only defines the macros
 * consumed by the LoRaWAN join code.
 *
 * NOTE: Consider keeping this file out of version control for real products.
 */
/* BEGIN GENERATED BY gen_euis.py (do not edit by hand) */
/* UNIT_ID: DEMO-0023 */
#define LORAWAN_DEV_EUI                                                        \
  { 0x46, 0x4c, 0x58, 0xda, 0x52, 0x4d, 0xcf, 0x74 }

#define LORAWAN_JOIN_EUI                                                        \
  { 0x92, 0xc8, 0x0f, 0x3e, 0x44, 0xbb, 0xc3, 0xd3 }

#define LORAWAN_APP_KEY                                                        \
  {                                                                            \
    0xab, 0xe3, 0xa1, 0x88, 0x0c, 0x35, 0x0b, 0x59, 0x8a, 0x0f, 0x29, 0x7b,    \
        0x53, 0x4e, 0x1b, 0x2a                                                 \
  }
/* END GENERATED BY gen_euis.py */


/*
 * Alternative key sets (kept here for convenience; comment/uncomment as needed)
 */
//DEMO-0018","464C58CDD531ADA8","F619DF61FC348046","BB82A6B87464F501094596A0FE8EDEA2","2026-09-02T21:28:51Z","1.5.0","1.4.1","FLEXBOX_PLUS","MRS","Marseille Provence Airport","Restroom"
// #define LORAWAN_DEV_EUI  { 0x46, 0x4c, 0x58, 0xcd, 0xd5, 0x31, 0xad, 0xa8 }
// #define LORAWAN_JOIN_EUI { 0xf6, 0x19, 0xdf, 0x61, 0xfc, 0x34, 0x80, 0x46 }
// #define LORAWAN_APP_KEY  { 0xbb, 0x82, 0xa6, 0xb8, 0x74, 0x64, 0xf5, 0x01, 0x09, 0x45, 0x96, 0xa0, 0xfe, 0x8e, 0xde, 0xa2 }

#endif /* EUI_KEYS_H */
