#ifndef EUI_KEYS_H
#define EUI_KEYS_H

/*
 * LoRaWAN identifiers/keys
 *
 * Keep these isolated from application logic so they are easy to rotate and
 * audit. This header is intentionally simple: it only defines the macros
 * consumed by the LoRaWAN join code.
 *
 * NOTE: Consider keeping this file out of version control for real products.
 */
/* BEGIN GENERATED BY gen_euis.py (do not edit by hand) */
/* UNIT_ID: UNIT-0146 */
#define LORAWAN_DEV_EUI                                                        \
  { 0x46, 0x4c, 0x58, 0x77, 0xa3, 0x34, 0x23, 0xcd }

#define LORAWAN_JOIN_EUI                                                        \
  { 0x12, 0xd2, 0x2d, 0x4e, 0xee, 0x15, 0x63, 0xd8 }

#define LORAWAN_APP_KEY                                                        \
  {                                                                            \
    0x58, 0x89, 0x0a, 0x26, 0x24, 0x74, 0x53, 0x73, 0x03, 0xa2, 0x6a, 0x12,    \
        0x1f, 0x6c, 0xe4, 0x6e                                                 \
  }
/* END GENERATED BY gen_euis.py */
/*
 * Alternative key sets (kept here for convenience; comment/uncomment as needed)
 *
 * #define LORAWAN_DEV_EUI  { ... }
 * #define LORAWAN_JOIN_EUI { ... }
 * #define LORAWAN_APP_KEY  { ... }
 */

#endif /* EUI_KEYS_H */
