#ifndef EUI_KEYS_H
#define EUI_KEYS_H

/*
 * LoRaWAN identifiers/keys
 *
 * Keep these isolated from application logic so they are easy to rotate and
 * audit. This header is intentionally simple: it only defines the macros
 * consumed by the LoRaWAN join code.
 *
 * NOTE: Consider keeping this file out of version control for real products.
 */

/* BEGIN GENERATED BY gen_euis.py (do not edit by hand) */
#define LORAWAN_DEV_EUI                                                        \
  { 0x46, 0x4c, 0x58, 0x9e, 0x94, 0x2d, 0x85, 0x81 }

#define LORAWAN_JOIN_EUI                                                       \
  { 0xea, 0x45, 0x94, 0xa4, 0x31, 0x1a, 0x66, 0x77 }

#define LORAWAN_APP_KEY                                                        \
  {                                                                            \
    0x14, 0x63, 0x0e, 0x64, 0xec, 0x6b, 0x9a, 0x8b, 0x84, 0xf9, 0xb0, 0x59,    \
        0xbb, 0xeb, 0xac, 0x22                                                 \
  }
/* END GENERATED BY gen_euis.py */

/*
 * Alternative key sets (kept here for convenience; comment/uncomment as needed)
 *
 * #define LORAWAN_DEV_EUI  { ... }
 * #define LORAWAN_JOIN_EUI { ... }
 * #define LORAWAN_APP_KEY  { ... }
 */

#endif /* EUI_KEYS_H */
