#ifndef EUI_KEYS_H
#define EUI_KEYS_H

/*
 * LoRaWAN identifiers/keys
 *
 * Keep these isolated from application logic so they are easy to rotate and
 * audit. This header is intentionally simple: it only defines the macros
 * consumed by the LoRaWAN join code.
 *
 * NOTE: Consider keeping this file out of version control for real products.
 */

/* BEGIN GENERATED BY gen_euis.py (do not edit by hand) */
#define LORAWAN_DEV_EUI                                                        \
  { 0x46, 0x4c, 0x58, 0x71, 0x81, 0x32, 0xe9, 0x08 }

#define LORAWAN_JOIN_EUI                                                       \
  { 0xea, 0xf2, 0x42, 0x8a, 0x14, 0xdb, 0xfd, 0x07 }

#define LORAWAN_APP_KEY                                                        \
  {                                                                            \
    0xdb, 0x6c, 0xe8, 0x11, 0xb1, 0xda, 0xb5, 0x55, 0x7f, 0x8b, 0xbc, 0x33,    \
        0xf0, 0x0d, 0x85, 0x0f                                                 \
  }
/* END GENERATED BY gen_euis.py */

/*
 * Alternative key sets (kept here for convenience; comment/uncomment as needed)
 *
 * #define LORAWAN_DEV_EUI  { ... }
 * #define LORAWAN_JOIN_EUI { ... }
 * #define LORAWAN_APP_KEY  { ... }
 */

#endif /* EUI_KEYS_H */
