# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# LoRaWAN
CONFIG_LORA=y
CONFIG_LORAWAN=y
CONFIG_LORAMAC_REGION_US915=y
CONFIG_TEST_RANDOM_GENERATOR=y

# Stack Sizes (increased for stability)
CONFIG_MAIN_STACK_SIZE=32768
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=32768

# System
CONFIG_REBOOT=y
CONFIG_SPI=y

# UART
# CONFIG_SERIAL=y
# CONFIG_UART=y
# CONFIG_UART_NRFX=y
# CONFIG_UART_NRFX_UARTE=y
# CONFIG_UART_CONSOLE=y
# CONFIG_UART_INTERRUPT_DRIVEN=y
# CONFIG_UART_LINE_CTRL=y

#GPIO
CONFIG_GPIO=y

# NFC PN5180
CONFIG_PN5180=y
CONFIG_PN5180_LOG_LEVEL=4
# CONFIG_PN5180_INIT_PRIORITY=50

#RTOS 
CONFIG_MULTITHREADING=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_INIT_STACKS=y
CONFIG_STACK_CANARIES=y

# Memory Protection
CONFIG_MPU=y
CONFIG_ARM_MPU=y
CONFIG_MPU_STACK_GUARD=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

# Memory Management
CONFIG_HEAP_MEM_POOL_SIZE=8192