#!/usr/bin/env python3
"""
Generate per-device LoRaWAN identifiers/keys and write them into app/include/eui_keys.h,
update app/include/sys_config.h (unit id + PROVISION_UTC timestamps between markers),
append to
onboarding/eui_registry*.csv, and align app/prj.conf + app/boards overlay with the
selected region (US915 + LR62E vs EU868 + Seeed WIO).

Usage (from repo root v1.1):
  python onboarding/gen_euis.py                    # US915: default registry + build profile
  python onboarding/gen_euis.py --region eu868   # EU868 (same as --EU)
  python onboarding/gen_euis.py --EU
  python onboarding/gen_euis.py --sync-build-only --region eu868   # overlay + prj only (no keys/CSV)
  python onboarding/gen_euis.py --stamp-provision-only             # DEVICE_PROVISION_* UTC only (no EUIs)

Recommended flashing flow:
  python onboarding/gen_euis.py && cd app && west flash --runner nrfjprog

Notes:
- DevEUI / JoinEUI are generated as locally-administered EUI-64 values:
  multicast bit cleared, local bit set.
- DevEUI is generated with a fixed 3-byte prefix (0x46, 0x4C, 0x58) and 5 random bytes.
- AppKey is 16 random bytes.
- Collisions are checked across BOTH eui_registry.csv and eui_registry_EU868.csv
  so that generated DevEUI/JoinEUI/AppKey are unique in either region.
"""

from __future__ import annotations

import argparse
import csv
import re
import secrets
import sys
from datetime import datetime, timezone
from pathlib import Path


# Script lives in onboarding/; app is at repo root.
ONBOARDING_DIR = Path(__file__).resolve().parent
REPO_ROOT = ONBOARDING_DIR.parent
EUI_KEYS_H = REPO_ROOT / "app" / "include" / "eui_keys.h"
SYS_CONFIG_H = REPO_ROOT / "app" / "include" / "sys_config.h"
PRJ_CONF = REPO_ROOT / "app" / "prj.conf"
BOARD_OVERLAY = REPO_ROOT / "app" / "boards" / "nrf52840dk_nrf52840.overlay"
REGISTRY_CSV_DEFAULT = ONBOARDING_DIR / "eui_registry.csv"
REGISTRY_CSV_EU868 = ONBOARDING_DIR / "eui_registry_EU868.csv"


BEGIN_MARKER = "/* BEGIN GENERATED BY gen_euis.py (do not edit by hand) */"
END_MARKER = "/* END GENERATED BY gen_euis.py */"

UNIT_ID_SYS_BEGIN = "/* BEGIN UNIT_ID (gen_euis.py) — do not edit by hand */"
UNIT_ID_SYS_END = "/* END UNIT_ID (gen_euis.py) */"

PROVISION_UTC_BEGIN = "/* BEGIN PROVISION_UTC (gen_euis.py) — do not edit by hand */"
PROVISION_UTC_END = "/* END PROVISION_UTC (gen_euis.py) */"
PROVISION_ISO_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")

PRJ_REGION_BEGIN = "# BEGIN LORAWAN_REGION (gen_euis.py)"
PRJ_REGION_END = "# END LORAWAN_REGION (gen_euis.py)"

OVERLAY_RADIO_BEGIN = "\t/* BEGIN LORA_RADIO_PROFILE (gen_euis.py) */"
OVERLAY_RADIO_END = "\t/* END LORA_RADIO_PROFILE (gen_euis.py) */"

# Inner block only (between markers, after newline following BEGIN line).
PRJ_INNER_US915 = "CONFIG_LORAMAC_REGION_US915=y\n# CONFIG_LORAMAC_REGION_EU868=y\n"
PRJ_INNER_EU868 = "# CONFIG_LORAMAC_REGION_US915=y\nCONFIG_LORAMAC_REGION_EU868=y\n"

OVERLAY_INNER_US915 = """\tlora_semtech_sx1262mb2das: sx1262@0 {
\t\tcompatible = "semtech,sx1262";
\t\treg = <0>;
\t\tspi-max-frequency = <7000000>;
\t\tlabel = "SX1262";
\t\treset-gpios = <&arduino_header 0 GPIO_ACTIVE_LOW>;
\t\tbusy-gpios = <&gpio0 31 GPIO_ACTIVE_HIGH>;
\t\tantenna-enable-gpios = <&arduino_header 14 GPIO_ACTIVE_HIGH>;
\t\tdio1-gpios = <&gpio0 19 (GPIO_PULL_DOWN | GPIO_ACTIVE_HIGH)>;
\t\tdio2-tx-enable;
\t\ttcxo-power-startup-delay-ms = <10>;
\t\tstatus = "okay";
\t};
"""

OVERLAY_INNER_EU868 = """\tlora_semtech_sx1262mb2das: sx1262@0 {
\t\tcompatible = "semtech,sx1262";
\t\treg = <0>;
\t\tspi-max-frequency = <7000000>;
\t\tlabel = "SX1262";
\t\treset-gpios = <&arduino_header 0 GPIO_ACTIVE_LOW>;
\t\tbusy-gpios  = <&gpio0 31 GPIO_ACTIVE_HIGH>;
\t\tdio1-gpios  = <&gpio0 19 (GPIO_PULL_DOWN | GPIO_ACTIVE_HIGH)>;
\t\tdio3-tcxo-voltage = <0x02>;
\t\ttcxo-power-startup-delay-ms = <10>;
\t\tdio2-tx-enable;
\t\tstatus = "okay";
\t};
"""

DEV_EUI_PREFIX = bytes.fromhex("46 4C 58")  # Fixed DevEUI prefix (3 bytes)
REGISTRY_FIELDS = ["asset_id", "dev_eui", "join_eui", "app_key"]


def _fmt_c_array_hex(bytes_: bytes) -> str:
    # "0x12, 0x34, ..."
    return ", ".join(f"0x{b:02x}" for b in bytes_)


def _fmt_eui_define(name: str, eui: bytes) -> str:
    if len(eui) != 8:
        raise ValueError("EUI must be 8 bytes")
    return (
        f"#define {name}                                                        \\\n"
        f"  {{ {_fmt_c_array_hex(eui)} }}\n"
    )


def _fmt_app_key_define(app_key: bytes) -> str:
    if len(app_key) != 16:
        raise ValueError("AppKey must be 16 bytes")
    # Wrap similarly to existing style.
    first = _fmt_c_array_hex(app_key[:12])
    last = _fmt_c_array_hex(app_key[12:])
    return (
        "#define LORAWAN_APP_KEY                                                        \\\n"
        "  {                                                                            \\\n"
        f"    {first},    \\\n"
        f"        {last}                                                 \\\n"
        "  }\n"
    )


def _eui64_local() -> bytes:
    b = bytearray(secrets.token_bytes(8))
    # EUI-64 first octet: bit0 = multicast, bit1 = local (U/L)
    b[0] = (b[0] | 0x02) & 0xFE
    return bytes(b)


def _dev_eui() -> bytes:
    """
    Generate an EUI-64 DevEUI that always begins with DEV_EUI_PREFIX, with the
    remaining bytes randomized.
    """
    if len(DEV_EUI_PREFIX) != 3:
        raise ValueError("DEV_EUI_PREFIX must be exactly 3 bytes")
    suffix = secrets.token_bytes(8 - len(DEV_EUI_PREFIX))
    dev = DEV_EUI_PREFIX + suffix
    # Ensure EUI-64 local-admin semantics even if prefix changes in the future.
    b = bytearray(dev)
    b[0] = (b[0] | 0x02) & 0xFE
    return bytes(b)


def _app_key() -> bytes:
    return secrets.token_bytes(16)


def _colon_hex(bytes_: bytes) -> str:
    return ":".join(f"{b:02X}" for b in bytes_)


def _plain_hex(bytes_: bytes) -> str:
    return "".join(f"{b:02X}" for b in bytes_)


def _normalize_hex_string(s: str) -> str:
    # Accept either "AA:BB:.." or "AABB.." and normalize to uppercase plain hex.
    return re.sub(r"[^0-9A-Fa-f]", "", (s or "")).upper()


def _read_existing_registry(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        return list(reader)


def _next_asset_id(existing_rows: list[dict[str, str]]) -> str:
    # Simple sequential ID: UNIT-0001, UNIT-0002, ...
    max_n = 0
    for r in existing_rows:
        aid = (r.get("asset_id") or "").strip()
        m = re.fullmatch(r"UNIT-(\d{4})", aid)
        if m:
            max_n = max(max_n, int(m.group(1)))
    return f"UNIT-{max_n + 1:04d}"


def _replace_between_markers(contents: str, begin_marker: str, end_marker: str, new_inner: str) -> str:
    """Replace everything after the begin line through (exclusive) the end marker line."""
    bi = contents.find(begin_marker)
    if bi < 0:
        raise RuntimeError(
            f"Missing begin marker {begin_marker!r} in file (expected provisioning markers)."
        )
    line_end = contents.find("\n", bi)
    if line_end < 0:
        raise RuntimeError(f"Begin marker line has no newline: {begin_marker!r}")
    start_inner = line_end + 1
    ei = contents.find(end_marker, start_inner)
    if ei < 0:
        raise RuntimeError(
            f"Missing end marker {end_marker!r} after begin marker (expected provisioning markers)."
        )
    return contents[:start_inner] + new_inner + contents[ei:]


def _replace_sys_config_unit_id(contents: str, asset_id: str) -> str:
    """Sync DEVICE_UNIT_ID_STRING in sys_config.h (markers must exist)."""
    if UNIT_ID_SYS_BEGIN not in contents or UNIT_ID_SYS_END not in contents:
        raise RuntimeError(
            f"Missing unit-id markers in {SYS_CONFIG_H}. "
            f"Expected:\n  {UNIT_ID_SYS_BEGIN}\n  {UNIT_ID_SYS_END}"
        )
    if not re.fullmatch(r"[A-Za-z0-9._-]+", asset_id or ""):
        raise ValueError(f"asset_id unsafe for C string: {asset_id!r}")
    start = contents.index(UNIT_ID_SYS_BEGIN)
    end_idx = contents.index(UNIT_ID_SYS_END)
    end_line = contents.find("\n", end_idx)
    if end_line == -1:
        end_line = len(contents)
    before = contents[:start]
    after = contents[end_line + 1 :]
    block = (
        f"{UNIT_ID_SYS_BEGIN}\n"
        f'#define DEVICE_UNIT_ID_STRING "{asset_id}"\n'
        f"{UNIT_ID_SYS_END}\n"
    )
    return before + block + after


def _replace_sys_config_provision_utc(
    contents: str, unix_ts: int, iso8601_z: str
) -> str:
    """Sync DEVICE_PROVISION_* macros (markers must exist)."""
    if PROVISION_UTC_BEGIN not in contents or PROVISION_UTC_END not in contents:
        raise RuntimeError(
            f"Missing PROVISION_UTC markers in {SYS_CONFIG_H}. "
            f"Expected:\n  {PROVISION_UTC_BEGIN}\n  {PROVISION_UTC_END}"
        )
    if unix_ts < 0:
        raise ValueError(f"unix_ts must be nonnegative, got {unix_ts}")
    if not PROVISION_ISO_RE.fullmatch(iso8601_z):
        raise ValueError(f"iso8601_z must match ...Z format, got {iso8601_z!r}")
    start = contents.index(PROVISION_UTC_BEGIN)
    end_idx = contents.index(PROVISION_UTC_END)
    end_line = contents.find("\n", end_idx)
    if end_line == -1:
        end_line = len(contents)
    before = contents[:start]
    after = contents[end_line + 1 :]
    block = (
        f"{PROVISION_UTC_BEGIN}\n"
        f"#define DEVICE_PROVISION_UNIX_UTC {unix_ts}ULL\n"
        f'#define DEVICE_PROVISION_ISO8601_UTC "{iso8601_z}"\n'
        f"{PROVISION_UTC_END}\n"
    )
    return before + block + after


def _replace_generated_section(contents: str, generated_block: str) -> str:
    """
    Replace the region between BEGIN_MARKER and END_MARKER.
    This avoids fragile regex matching on multi-line macro formatting.
    """
    if BEGIN_MARKER not in contents or END_MARKER not in contents:
        raise RuntimeError(
            f"Missing generated markers in {EUI_KEYS_H}. "
            f"Expected to find both:\n  {BEGIN_MARKER}\n  {END_MARKER}"
        )

    start = contents.index(BEGIN_MARKER)
    end = contents.index(END_MARKER)
    end_line = contents.find("\n", end)
    if end_line == -1:
        end_line = len(contents)

    before = contents[:start]
    after = contents[end_line + 1 :]
    return before + generated_block + after


def _migrate_registry_drop_timestamp(path: Path) -> None:
    """
    If the registry CSV exists in the old format (with 'timestamp_utc' column),
    rewrite it into the new format (without timestamps).
    """
    if not path.exists():
        return

    text = path.read_text(encoding="utf-8")
    if not text.strip():
        return

    lines = text.splitlines()
    header = lines[0] if lines else ""
    if "timestamp_utc" not in header.split(","):
        return

    # Read all rows from old CSV and rewrite without timestamp_utc.
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    tmp = path.with_suffix(".csv.tmp")
    with tmp.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=REGISTRY_FIELDS)
        writer.writeheader()
        for r in rows:
            writer.writerow({k: (r.get(k) or "") for k in REGISTRY_FIELDS})

    tmp.replace(path)


def _atomic_write(path: Path, text: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def apply_build_profile(region: str) -> None:
    """Set prj.conf LoRaWAN region and board overlay radio profile (us915 vs eu868)."""
    region = region.lower()
    if region == "us915":
        prj_inner = PRJ_INNER_US915
        ovl_inner = OVERLAY_INNER_US915
    elif region == "eu868":
        prj_inner = PRJ_INNER_EU868
        ovl_inner = OVERLAY_INNER_EU868
    else:
        raise ValueError(f"Unknown region: {region!r}")

    if not PRJ_CONF.exists():
        raise RuntimeError(f"{PRJ_CONF} not found")
    if not BOARD_OVERLAY.exists():
        raise RuntimeError(f"{BOARD_OVERLAY} not found")

    prj_text = PRJ_CONF.read_text(encoding="utf-8")
    prj_text = _replace_between_markers(prj_text, PRJ_REGION_BEGIN, PRJ_REGION_END, prj_inner)
    _atomic_write(PRJ_CONF, prj_text)

    ovl_text = BOARD_OVERLAY.read_text(encoding="utf-8")
    ovl_text = _replace_between_markers(ovl_text, OVERLAY_RADIO_BEGIN, OVERLAY_RADIO_END, ovl_inner)
    _atomic_write(BOARD_OVERLAY, ovl_text)


def _resolve_region(args: argparse.Namespace) -> str:
    eu_flag = bool(getattr(args, "EU", False))
    region_arg = getattr(args, "region", None)
    if eu_flag and region_arg and region_arg != "eu868":
        raise ValueError("--EU implies eu868; do not combine with --region us915")
    if eu_flag:
        return "eu868"
    if region_arg:
        return region_arg.lower()
    return "us915"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate LoRaWAN EUIs/keys, update headers/registry, and sync region build files."
    )
    parser.add_argument(
        "--region",
        choices=("us915", "eu868"),
        default=None,
        help="LoRaWAN region + radio profile + registry CSV family. Default: us915",
    )
    parser.add_argument(
        "--EU",
        action="store_true",
        help="Alias for --region eu868 (eui_registry_EU868.csv + EU868 build profile)",
    )
    parser.add_argument(
        "--sync-build-only",
        action="store_true",
        help="Only update app/prj.conf and board overlay for the selected region; "
        "do not generate keys or modify CSV/headers.",
    )
    parser.add_argument(
        "--stamp-provision-only",
        action="store_true",
        dest="stamp_provision_only",
        help="Only set DEVICE_PROVISION_UNIX_UTC / DEVICE_PROVISION_ISO8601_UTC in "
        "sys_config.h from current UTC; does not touch keys, CSV, unit id, or build profile.",
    )
    args = parser.parse_args()

    if args.sync_build_only and args.stamp_provision_only:
        print(
            "ERROR: use either --sync-build-only or --stamp-provision-only, not both",
            file=sys.stderr,
        )
        return 2
    if args.stamp_provision_only:
        if args.EU or args.region is not None:
            print(
                "ERROR: --stamp-provision-only does not use --region/--EU",
                file=sys.stderr,
            )
            return 2
        if not SYS_CONFIG_H.exists():
            print(f"ERROR: {SYS_CONFIG_H} not found", file=sys.stderr)
            return 2
        prov_now = datetime.now(timezone.utc)
        provision_unix = int(prov_now.timestamp())
        provision_iso = prov_now.strftime("%Y-%m-%dT%H:%M:%SZ")
        try:
            sc_text = SYS_CONFIG_H.read_text(encoding="utf-8")
            sc_text = _replace_sys_config_provision_utc(sc_text, provision_unix, provision_iso)
            _atomic_write(SYS_CONFIG_H, sc_text)
        except (RuntimeError, ValueError) as e:
            print(f"ERROR: {e}", file=sys.stderr)
            return 2
        print("")
        print("=== Provision stamp only (no EUI/key/CSV/prj/overlay changes) ===")
        print(f"DEVICE_PROVISION_UNIX_UTC      = {provision_unix}ULL")
        print(f'DEVICE_PROVISION_ISO8601_UTC    = "{provision_iso}"')
        print(f"Updated: {SYS_CONFIG_H}")
        print("")
        print("Rebuild/flash to pick this up:")
        print("  cd app && west build ... && west flash ...")
        print("")
        return 0

    try:
        region = _resolve_region(args)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    registry_csv = REGISTRY_CSV_EU868 if region == "eu868" else REGISTRY_CSV_DEFAULT

    if args.sync_build_only:
        try:
            apply_build_profile(region)
        except (RuntimeError, ValueError) as e:
            print(f"ERROR: {e}", file=sys.stderr)
            return 2
        print("")
        print("=== Build profile only (no EUI/CSV changes) ===")
        print(f"Region : {region}")
        print(f"Updated: {PRJ_CONF}")
        print(f"Updated: {BOARD_OVERLAY}")
        print("")
        return 0

    if not EUI_KEYS_H.exists():
        print(f"ERROR: {EUI_KEYS_H} not found", file=sys.stderr)
        return 2
    if not SYS_CONFIG_H.exists():
        print(f"ERROR: {SYS_CONFIG_H} not found", file=sys.stderr)
        return 2

    _migrate_registry_drop_timestamp(REGISTRY_CSV_DEFAULT)
    _migrate_registry_drop_timestamp(REGISTRY_CSV_EU868)

    existing_rows = _read_existing_registry(registry_csv)
    rows_default = _read_existing_registry(REGISTRY_CSV_DEFAULT)
    rows_eu = _read_existing_registry(REGISTRY_CSV_EU868)
    all_rows = rows_default + rows_eu

    print(f"Target registry: {registry_csv} (existing rows: {len(existing_rows)})")
    print(f"Region / build profile: {region}")
    print(
        f"Collision check: both {REGISTRY_CSV_DEFAULT.name} ({len(rows_default)}) + "
        f"{REGISTRY_CSV_EU868.name} ({len(rows_eu)})"
    )

    existing_dev_euis = {_normalize_hex_string(r.get("dev_eui", "")) for r in all_rows}
    existing_join_euis = {_normalize_hex_string(r.get("join_eui", "")) for r in all_rows}
    existing_app_keys = {_normalize_hex_string(r.get("app_key", "")) for r in all_rows}

    # Generate unique DevEUI (extremely unlikely to collide, but we check anyway)
    for _ in range(100):
        dev_eui = _dev_eui()
        dev_eui_str = _plain_hex(dev_eui)
        if dev_eui_str.upper() not in existing_dev_euis:
            break
    else:
        print("ERROR: failed to generate a unique DevEUI after many attempts", file=sys.stderr)
        return 3

    # Generate unique JoinEUI (also extremely unlikely to collide, but we check anyway)
    for _ in range(100):
        join_eui = _eui64_local()
        join_eui_str = _plain_hex(join_eui)
        if join_eui_str.upper() not in existing_join_euis:
            break
    else:
        print("ERROR: failed to generate a unique JoinEUI after many attempts", file=sys.stderr)
        return 4

    # AppKey collisions are astronomically unlikely, but keep the registry "strictly unique".
    for _ in range(100):
        app_key = _app_key()
        app_key_str = _plain_hex(app_key)
        if app_key_str.upper() not in existing_app_keys:
            break
    else:
        print("ERROR: failed to generate a unique AppKey after many attempts", file=sys.stderr)
        return 5

    # Next registry id (same string written to headers and CSV)
    asset_id = _next_asset_id(existing_rows)

    prov_now = datetime.now(timezone.utc)
    provision_unix = int(prov_now.timestamp())
    provision_iso = prov_now.strftime("%Y-%m-%dT%H:%M:%SZ")

    # Update eui_keys.h (generated section + UNIT_ID comment)
    contents = EUI_KEYS_H.read_text(encoding="utf-8")
    generated_block = (
        f"{BEGIN_MARKER}\n"
        f"/* UNIT_ID: {asset_id} */\n"
        + _fmt_eui_define("LORAWAN_DEV_EUI", dev_eui)
        + "\n"
        + _fmt_eui_define("LORAWAN_JOIN_EUI", join_eui)
        + "\n"
        + _fmt_app_key_define(app_key)
        + f"{END_MARKER}\n"
    )
    contents = _replace_generated_section(contents, generated_block)

    tmp = EUI_KEYS_H.with_suffix(".h.tmp")
    tmp.write_text(contents, encoding="utf-8")
    tmp.replace(EUI_KEYS_H)

    # Update sys_config.h DEVICE_UNIT_ID_STRING (between markers)
    sc_text = SYS_CONFIG_H.read_text(encoding="utf-8")
    sc_text = _replace_sys_config_unit_id(sc_text, asset_id)
    sc_tmp = SYS_CONFIG_H.with_suffix(".h.tmp")
    sc_tmp.write_text(sc_text, encoding="utf-8")
    sc_tmp.replace(SYS_CONFIG_H)

    # Append to registry
    new_row = {
        "asset_id": asset_id,
        # Store as plain uppercase hex for easy copy/paste/import
        "dev_eui": _plain_hex(dev_eui),
        "join_eui": _plain_hex(join_eui),
        "app_key": _plain_hex(app_key),
    }

    write_header = (not registry_csv.exists()) or registry_csv.stat().st_size == 0
    with registry_csv.open("a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=REGISTRY_FIELDS,
        )
        if write_header:
            writer.writeheader()
        writer.writerow(new_row)

    try:
        apply_build_profile(region)
    except (RuntimeError, ValueError) as e:
        print(f"ERROR: build profile update failed: {e}", file=sys.stderr)
        return 6

    print("")
    print("=== Provisioned credentials ===")
    print(f"Provision UTC: {provision_iso} (unix={provision_unix})")
    print(f"Asset ID : {asset_id}")
    print(f"DevEUI   : {_colon_hex(dev_eui)}")
    print(f"JoinEUI  : {_colon_hex(join_eui)}")
    print(f"AppKey   : {_colon_hex(app_key)}")
    print("")
    print("CSV format (no colons):")
    print(f"DevEUI   : {new_row['dev_eui']}")
    print(f"JoinEUI  : {new_row['join_eui']}")
    print(f"AppKey   : {new_row['app_key']}")
    print("")
    print(f"Updated: {EUI_KEYS_H}")
    print(f"Updated: {SYS_CONFIG_H} (unit id + DEVICE_PROVISION_* UTC)")
    print(f"Updated: {PRJ_CONF} + {BOARD_OVERLAY} (region={region})")
    print(f"Appended registry row: {registry_csv}")
    print("")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
