#!/usr/bin/env python3
"""
Generate per-device LoRaWAN identifiers/keys and write them into app/include/eui_keys.h,
update app/include/sys_config.h (DEVICE_UNIT_ID_STRING between markers), then append to
onboarding/eui_registry.csv.

Usage (from repo root v1.1):
  python onboarding/gen_euis.py              # use eui_registry.csv (default)
  python onboarding/gen_euis.py --EU        # use eui_registry_EU868.csv
  # or: cd onboarding && python gen_euis.py

Recommended flashing flow:
  python onboarding/gen_euis.py && cd app && west flash --runner nrfjprog

Notes:
- DevEUI / JoinEUI are generated as locally-administered EUI-64 values:
  multicast bit cleared, local bit set.
- DevEUI is generated with a fixed 3-byte prefix (0x46, 0x4C, 0x58) and 5 random bytes.
- AppKey is 16 random bytes.
- Collisions are checked across BOTH eui_registry.csv and eui_registry_EU868.csv
  so that generated DevEUI/JoinEUI/AppKey are unique in either region.
"""

from __future__ import annotations

import argparse
import csv
import secrets
import sys
from pathlib import Path
import re


# Script lives in onboarding/; app is at repo root.
ONBOARDING_DIR = Path(__file__).resolve().parent
REPO_ROOT = ONBOARDING_DIR.parent
EUI_KEYS_H = REPO_ROOT / "app" / "include" / "eui_keys.h"
SYS_CONFIG_H = REPO_ROOT / "app" / "include" / "sys_config.h"
REGISTRY_CSV_DEFAULT = ONBOARDING_DIR / "eui_registry.csv"
REGISTRY_CSV_EU868 = ONBOARDING_DIR / "eui_registry_EU868.csv"


BEGIN_MARKER = "/* BEGIN GENERATED BY gen_euis.py (do not edit by hand) */"
END_MARKER = "/* END GENERATED BY gen_euis.py */"

UNIT_ID_SYS_BEGIN = "/* BEGIN UNIT_ID (gen_euis.py) — do not edit by hand */"
UNIT_ID_SYS_END = "/* END UNIT_ID (gen_euis.py) */"

DEV_EUI_PREFIX = bytes.fromhex("46 4C 58")  # Fixed DevEUI prefix (3 bytes)
REGISTRY_FIELDS = ["asset_id", "dev_eui", "join_eui", "app_key"]


def _fmt_c_array_hex(bytes_: bytes) -> str:
    # "0x12, 0x34, ..."
    return ", ".join(f"0x{b:02x}" for b in bytes_)


def _fmt_eui_define(name: str, eui: bytes) -> str:
    if len(eui) != 8:
        raise ValueError("EUI must be 8 bytes")
    return (
        f"#define {name}                                                        \\\n"
        f"  {{ {_fmt_c_array_hex(eui)} }}\n"
    )


def _fmt_app_key_define(app_key: bytes) -> str:
    if len(app_key) != 16:
        raise ValueError("AppKey must be 16 bytes")
    # Wrap similarly to existing style.
    first = _fmt_c_array_hex(app_key[:12])
    last = _fmt_c_array_hex(app_key[12:])
    return (
        "#define LORAWAN_APP_KEY                                                        \\\n"
        "  {                                                                            \\\n"
        f"    {first},    \\\n"
        f"        {last}                                                 \\\n"
        "  }\n"
    )


def _eui64_local() -> bytes:
    b = bytearray(secrets.token_bytes(8))
    # EUI-64 first octet: bit0 = multicast, bit1 = local (U/L)
    b[0] = (b[0] | 0x02) & 0xFE
    return bytes(b)


def _dev_eui() -> bytes:
    """
    Generate an EUI-64 DevEUI that always begins with DEV_EUI_PREFIX, with the
    remaining bytes randomized.
    """
    if len(DEV_EUI_PREFIX) != 3:
        raise ValueError("DEV_EUI_PREFIX must be exactly 3 bytes")
    suffix = secrets.token_bytes(8 - len(DEV_EUI_PREFIX))
    dev = DEV_EUI_PREFIX + suffix
    # Ensure EUI-64 local-admin semantics even if prefix changes in the future.
    b = bytearray(dev)
    b[0] = (b[0] | 0x02) & 0xFE
    return bytes(b)


def _app_key() -> bytes:
    return secrets.token_bytes(16)


def _colon_hex(bytes_: bytes) -> str:
    return ":".join(f"{b:02X}" for b in bytes_)

def _plain_hex(bytes_: bytes) -> str:
    return "".join(f"{b:02X}" for b in bytes_)

def _normalize_hex_string(s: str) -> str:
    # Accept either "AA:BB:.." or "AABB.." and normalize to uppercase plain hex.
    return re.sub(r"[^0-9A-Fa-f]", "", (s or "")).upper()


def _read_existing_registry(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        return list(reader)


def _next_asset_id(existing_rows: list[dict[str, str]]) -> str:
    # Simple sequential ID: UNIT-0001, UNIT-0002, ...
    max_n = 0
    for r in existing_rows:
        aid = (r.get("asset_id") or "").strip()
        m = re.fullmatch(r"UNIT-(\d{4})", aid)
        if m:
            max_n = max(max_n, int(m.group(1)))
    return f"UNIT-{max_n + 1:04d}"


def _replace_sys_config_unit_id(contents: str, asset_id: str) -> str:
    """Sync DEVICE_UNIT_ID_STRING in sys_config.h (markers must exist)."""
    if UNIT_ID_SYS_BEGIN not in contents or UNIT_ID_SYS_END not in contents:
        raise RuntimeError(
            f"Missing unit-id markers in {SYS_CONFIG_H}. "
            f"Expected:\n  {UNIT_ID_SYS_BEGIN}\n  {UNIT_ID_SYS_END}"
        )
    if not re.fullmatch(r"[A-Za-z0-9._-]+", asset_id or ""):
        raise ValueError(f"asset_id unsafe for C string: {asset_id!r}")
    start = contents.index(UNIT_ID_SYS_BEGIN)
    end_idx = contents.index(UNIT_ID_SYS_END)
    end_line = contents.find("\n", end_idx)
    if end_line == -1:
        end_line = len(contents)
    before = contents[:start]
    after = contents[end_line + 1 :]
    block = (
        f"{UNIT_ID_SYS_BEGIN}\n"
        f'#define DEVICE_UNIT_ID_STRING "{asset_id}"\n'
        f"{UNIT_ID_SYS_END}\n"
    )
    return before + block + after


def _replace_generated_section(contents: str, generated_block: str) -> str:
    """
    Replace the region between BEGIN_MARKER and END_MARKER.
    This avoids fragile regex matching on multi-line macro formatting.
    """
    if BEGIN_MARKER not in contents or END_MARKER not in contents:
        raise RuntimeError(
            f"Missing generated markers in {EUI_KEYS_H}. "
            f"Expected to find both:\n  {BEGIN_MARKER}\n  {END_MARKER}"
        )

    start = contents.index(BEGIN_MARKER)
    end = contents.index(END_MARKER)
    end_line = contents.find("\n", end)
    if end_line == -1:
        end_line = len(contents)

    before = contents[:start]
    after = contents[end_line + 1 :]
    return before + generated_block + after


def _migrate_registry_drop_timestamp(path: Path) -> None:
    """
    If the registry CSV exists in the old format (with 'timestamp_utc' column),
    rewrite it into the new format (without timestamps).
    """
    if not path.exists():
        return

    text = path.read_text(encoding="utf-8")
    if not text.strip():
        return

    lines = text.splitlines()
    header = lines[0] if lines else ""
    if "timestamp_utc" not in header.split(","):
        return

    # Read all rows from old CSV and rewrite without timestamp_utc.
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    tmp = path.with_suffix(".csv.tmp")
    with tmp.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=REGISTRY_FIELDS)
        writer.writeheader()
        for r in rows:
            writer.writerow({k: (r.get(k) or "") for k in REGISTRY_FIELDS})

    tmp.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate LoRaWAN EUIs/keys and append to registry CSV.")
    parser.add_argument(
        "--EU",
        action="store_true",
        help="Use EU868 registry (eui_registry_EU868.csv). Default: eui_registry.csv",
    )
    args = parser.parse_args()
    registry_csv = REGISTRY_CSV_EU868 if args.EU else REGISTRY_CSV_DEFAULT

    if not EUI_KEYS_H.exists():
        print(f"ERROR: {EUI_KEYS_H} not found", file=sys.stderr)
        return 2
    if not SYS_CONFIG_H.exists():
        print(f"ERROR: {SYS_CONFIG_H} not found", file=sys.stderr)
        return 2

    _migrate_registry_drop_timestamp(REGISTRY_CSV_DEFAULT)
    _migrate_registry_drop_timestamp(REGISTRY_CSV_EU868)

    existing_rows = _read_existing_registry(registry_csv)
    rows_default = _read_existing_registry(REGISTRY_CSV_DEFAULT)
    rows_eu = _read_existing_registry(REGISTRY_CSV_EU868)
    all_rows = rows_default + rows_eu

    print(f"Target registry: {registry_csv} (existing rows: {len(existing_rows)})")
    print(f"Collision check: both {REGISTRY_CSV_DEFAULT.name} ({len(rows_default)}) + {REGISTRY_CSV_EU868.name} ({len(rows_eu)})")

    existing_dev_euis = {_normalize_hex_string(r.get("dev_eui", "")) for r in all_rows}
    existing_join_euis = {_normalize_hex_string(r.get("join_eui", "")) for r in all_rows}
    existing_app_keys = {_normalize_hex_string(r.get("app_key", "")) for r in all_rows}

    # Generate unique DevEUI (extremely unlikely to collide, but we check anyway)
    for _ in range(100):
        dev_eui = _dev_eui()
        dev_eui_str = _plain_hex(dev_eui)
        if dev_eui_str.upper() not in existing_dev_euis:
            break
    else:
        print("ERROR: failed to generate a unique DevEUI after many attempts", file=sys.stderr)
        return 3

    # Generate unique JoinEUI (also extremely unlikely to collide, but we check anyway)
    for _ in range(100):
        join_eui = _eui64_local()
        join_eui_str = _plain_hex(join_eui)
        if join_eui_str.upper() not in existing_join_euis:
            break
    else:
        print("ERROR: failed to generate a unique JoinEUI after many attempts", file=sys.stderr)
        return 4

    # AppKey collisions are astronomically unlikely, but keep the registry "strictly unique".
    for _ in range(100):
        app_key = _app_key()
        app_key_str = _plain_hex(app_key)
        if app_key_str.upper() not in existing_app_keys:
            break
    else:
        print("ERROR: failed to generate a unique AppKey after many attempts", file=sys.stderr)
        return 5

    # Next registry id (same string written to headers and CSV)
    asset_id = _next_asset_id(existing_rows)

    # Update eui_keys.h (generated section + UNIT_ID comment)
    contents = EUI_KEYS_H.read_text(encoding="utf-8")
    generated_block = (
        f"{BEGIN_MARKER}\n"
        f"/* UNIT_ID: {asset_id} */\n"
        + _fmt_eui_define("LORAWAN_DEV_EUI", dev_eui)
        + "\n"
        + _fmt_eui_define("LORAWAN_JOIN_EUI", join_eui)
        + "\n"
        + _fmt_app_key_define(app_key)
        + f"{END_MARKER}\n"
    )
    contents = _replace_generated_section(contents, generated_block)

    tmp = EUI_KEYS_H.with_suffix(".h.tmp")
    tmp.write_text(contents, encoding="utf-8")
    tmp.replace(EUI_KEYS_H)

    # Update sys_config.h DEVICE_UNIT_ID_STRING (between markers)
    sc_text = SYS_CONFIG_H.read_text(encoding="utf-8")
    sc_text = _replace_sys_config_unit_id(sc_text, asset_id)
    sc_tmp = SYS_CONFIG_H.with_suffix(".h.tmp")
    sc_tmp.write_text(sc_text, encoding="utf-8")
    sc_tmp.replace(SYS_CONFIG_H)

    # Append to registry
    new_row = {
        "asset_id": asset_id,
        # Store as plain uppercase hex for easy copy/paste/import
        "dev_eui": _plain_hex(dev_eui),
        "join_eui": _plain_hex(join_eui),
        "app_key": _plain_hex(app_key),
    }

    write_header = (not registry_csv.exists()) or registry_csv.stat().st_size == 0
    with registry_csv.open("a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=REGISTRY_FIELDS,
        )
        if write_header:
            writer.writeheader()
        writer.writerow(new_row)

    print("")
    print("=== Provisioned credentials ===")
    print(f"Asset ID : {asset_id}")
    print(f"DevEUI   : {_colon_hex(dev_eui)}")
    print(f"JoinEUI  : {_colon_hex(join_eui)}")
    print(f"AppKey   : {_colon_hex(app_key)}")
    print("")
    print("CSV format (no colons):")
    print(f"DevEUI   : {new_row['dev_eui']}")
    print(f"JoinEUI  : {new_row['join_eui']}")
    print(f"AppKey   : {new_row['app_key']}")
    print("")
    print(f"Updated: {EUI_KEYS_H}")
    print(f"Updated: {SYS_CONFIG_H} (DEVICE_UNIT_ID_STRING)")
    print(f"Appended registry row: {registry_csv}")
    print("")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


