#!/usr/bin/env python3
"""
Shared provisioning library: EUI/key generation, build profile sync, registry I/O.

Used by provision.py (primary CLI) and gen_euis.py (legacy shim).
"""

from __future__ import annotations

import argparse
import csv
import re
import secrets
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

ONBOARDING_DIR = Path(__file__).resolve().parent
REPO_ROOT = ONBOARDING_DIR.parent
EUI_KEYS_H = REPO_ROOT / "app" / "include" / "eui_keys.h"
ONBOARDING_CONFIG_H = REPO_ROOT / "app" / "include" / "onboarding_config.h"
SYS_CONFIG_H = REPO_ROOT / "app" / "include" / "sys_config.h"
PRJ_CONF = REPO_ROOT / "app" / "prj.conf"
PRJ_FLEXBOX_CONF = REPO_ROOT / "app" / "prj_flexbox.conf"
PRJ_FLEXBOX_PLUS_CONF = REPO_ROOT / "app" / "prj_flexbox_plus.conf"
BOARD_OVERLAY = REPO_ROOT / "app" / "boards" / "nrf52840dk_nrf52840.overlay"
FLEXBOX_PLUS_OVERLAY = (
    REPO_ROOT / "app" / "boards" / "nrf52840dk_nrf52840_flexbox_plus.overlay"
)
REGISTRY_DIR = ONBOARDING_DIR / "flexbox_euis"
DEMO_REGISTRY_DIR = REGISTRY_DIR / "demo_units"
REGISTRY_CSV_US915 = "eui_registry.csv"
REGISTRY_CSV_EU868 = "eui_registry_EU868.csv"

BEGIN_MARKER = "/* BEGIN GENERATED BY gen_euis.py (do not edit by hand) */"
END_MARKER = "/* END GENERATED BY gen_euis.py */"
UNIT_ID_SYS_BEGIN = "/* BEGIN UNIT_ID (gen_euis.py) — do not edit by hand */"
UNIT_ID_SYS_END = "/* END UNIT_ID (gen_euis.py) */"
PROVISION_UTC_BEGIN = "/* BEGIN PROVISION_UTC (gen_euis.py) — do not edit by hand */"
PROVISION_UTC_END = "/* END PROVISION_UTC (gen_euis.py) */"
PROVISION_ISO_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")

PRJ_REGION_BEGIN = "# BEGIN LORAWAN_REGION (gen_euis.py)"
PRJ_REGION_END = "# END LORAWAN_REGION (gen_euis.py)"
OVERLAY_RADIO_BEGIN = "\t/* BEGIN LORA_RADIO_PROFILE (gen_euis.py) */"
OVERLAY_RADIO_END = "\t/* END LORA_RADIO_PROFILE (gen_euis.py) */"

PRJ_INNER_US915 = "CONFIG_LORAMAC_REGION_US915=y\n# CONFIG_LORAMAC_REGION_EU868=y\n"
PRJ_INNER_EU868 = "# CONFIG_LORAMAC_REGION_US915=y\nCONFIG_LORAMAC_REGION_EU868=y\n"

# LR62E module (US915 only): antenna-enable, no dio3-tcxo.
OVERLAY_INNER_LR62 = """\tlora_semtech_sx1262mb2das: sx1262@0 {
\t\tcompatible = "semtech,sx1262";
\t\treg = <0>;
\t\tspi-max-frequency = <7000000>;
\t\tlabel = "SX1262";
\t\treset-gpios = <&arduino_header 0 GPIO_ACTIVE_LOW>;
\t\tbusy-gpios = <&gpio0 31 GPIO_ACTIVE_HIGH>;
\t\tantenna-enable-gpios = <&arduino_header 14 GPIO_ACTIVE_HIGH>;
\t\tdio1-gpios = <&gpio0 19 (GPIO_PULL_DOWN | GPIO_ACTIVE_HIGH)>;
\t\tdio2-tx-enable;
\t\ttcxo-power-startup-delay-ms = <10>;
\t\tstatus = "okay";
\t};
"""

# Seeed WIO SX1262 (EU868 + US915): dio3-tcxo-voltage.
OVERLAY_INNER_SEED = """\tlora_semtech_sx1262mb2das: sx1262@0 {
\t\tcompatible = "semtech,sx1262";
\t\treg = <0>;
\t\tspi-max-frequency = <7000000>;
\t\tlabel = "SX1262";
\t\treset-gpios = <&arduino_header 0 GPIO_ACTIVE_LOW>;
\t\tbusy-gpios  = <&gpio0 31 GPIO_ACTIVE_HIGH>;
\t\tdio1-gpios  = <&gpio0 19 (GPIO_PULL_DOWN | GPIO_ACTIVE_HIGH)>;
\t\tdio3-tcxo-voltage = <0x02>;
\t\ttcxo-power-startup-delay-ms = <10>;
\t\tdio2-tx-enable;
\t\tstatus = "okay";
\t};
"""

DEV_EUI_PREFIX = bytes.fromhex("46 4C 58")

REGISTRY_FIELDS = [
    "asset_id",
    "dev_eui",
    "join_eui",
    "app_key",
    "provision_utc",
    "fw_version",
    "hw_version",
    "hw_profile",
    "name_prefix",
    "tag_client",
    "decal_type",
]

FW_VERSION_STRING_RE = re.compile(r'#define\s+FW_VERSION_STRING\s+"([^"]*)"')
HW_VERSION_STRING_RE = re.compile(r'#define\s+HW_VERSION_STRING\s+"([^"]*)"')
DEVICE_HW_VARIANT_RE = re.compile(
    r"#define\s+DEVICE_HW_VARIANT\s+(FLEXBOX_PLUS|FLEXBOX)\b"
)
CONFIG_PN5180_Y_RE = re.compile(r"(?m)^CONFIG_PN5180=y\s*$")
CONFIG_SSD1683_Y_RE = re.compile(r"(?m)^CONFIG_SSD1683=y\s*$")
CONFIG_DISPLAY_Y_RE = re.compile(r"(?m)^CONFIG_DISPLAY=y\s*$")
CONFIG_LVGL_Y_RE = re.compile(r"(?m)^CONFIG_LVGL=y\s*$")
SSD1683_DT_RE = re.compile(r"compatible\s*=\s*\"solomon,ssd1683\"")
PN5180_DT_RE = re.compile(r"compatible\s*=\s*\"nxp,pn5180\"")
REGISTRY_NAME_PREFIX_STRING_RE = re.compile(
    r"#define\s+DEVICE_REGISTRY_NAME_PREFIX_STRING\s+\"([^\"]*)\""
)
REGISTRY_CLIENT_NAME_RE = re.compile(
    r"#define\s+DEVICE_REGISTRY_CLIENT_NAME\s+\"([^\"]*)\""
)
REGISTRY_DECAL_TYPE_RE = re.compile(
    r"#define\s+DEVICE_REGISTRY_DECAL_TYPE\s+\"([^\"]*)\""
)

VALID_HARDWARE = frozenset({"lr62", "seeed"})
VALID_REGIONS = frozenset({"us915", "eu868"})


@dataclass(frozen=True)
class BuildProfile:
    hardware: str
    region: str

    def __post_init__(self) -> None:
        if self.hardware not in VALID_HARDWARE:
            raise ValueError(f"unknown hardware {self.hardware!r}")
        if self.region not in VALID_REGIONS:
            raise ValueError(f"unknown region {self.region!r}")
        if self.hardware == "lr62" and self.region != "us915":
            raise ValueError("LR62E radio is US915-only; use --preset seeed-eu868 for EU868")


def registry_dir(*, test: bool) -> Path:
    return DEMO_REGISTRY_DIR if test else REGISTRY_DIR


def registry_csv_path(region: str, *, test: bool) -> Path:
    name = REGISTRY_CSV_EU868 if region == "eu868" else REGISTRY_CSV_US915
    return registry_dir(test=test) / name


def master_registry_paths() -> list[Path]:
    paths = [REGISTRY_DIR / REGISTRY_CSV_US915, REGISTRY_DIR / REGISTRY_CSV_EU868]
    return [p for p in paths if p.exists()]


def demo_registry_paths() -> list[Path]:
    paths = [
        DEMO_REGISTRY_DIR / REGISTRY_CSV_US915,
        DEMO_REGISTRY_DIR / REGISTRY_CSV_EU868,
    ]
    return [p for p in paths if p.exists()]


def collision_registry_paths(*, test: bool) -> list[Path]:
    """All CSV files checked when generating new keys (master + demo_units)."""
    seen: set[Path] = set()
    out: list[Path] = []
    for p in master_registry_paths() + demo_registry_paths():
        rp = p.resolve()
        if rp not in seen:
            seen.add(rp)
            out.append(p)
    return out


def apply_build_profile(profile: BuildProfile) -> None:
    if profile.region == "us915":
        prj_inner = PRJ_INNER_US915
    else:
        prj_inner = PRJ_INNER_EU868

    ovl_inner = (
        OVERLAY_INNER_LR62 if profile.hardware == "lr62" else OVERLAY_INNER_SEED
    )

    if not PRJ_CONF.exists():
        raise RuntimeError(f"{PRJ_CONF} not found")
    if not BOARD_OVERLAY.exists():
        raise RuntimeError(f"{BOARD_OVERLAY} not found")

    prj_text = PRJ_CONF.read_text(encoding="utf-8")
    prj_text = _replace_between_markers(
        prj_text, PRJ_REGION_BEGIN, PRJ_REGION_END, prj_inner
    )
    _atomic_write(PRJ_CONF, prj_text)

    ovl_text = BOARD_OVERLAY.read_text(encoding="utf-8")
    ovl_text = _replace_between_markers(
        ovl_text, OVERLAY_RADIO_BEGIN, OVERLAY_RADIO_END, ovl_inner
    )
    _atomic_write(BOARD_OVERLAY, ovl_text)


_LEGACY_HW_PROFILE_ALIASES = {"EPD_NFC": "FLEXBOX_PLUS", "NFC_BUTTONS": "FLEXBOX"}


def normalize_asset_id(unit: str, *, test: bool = False) -> str:
    """Accept UNIT-0322, unit-322, or bare 322 (demo: DEMO-0001 / 1 with --test)."""
    u = (unit or "").strip()
    if not u:
        raise ValueError("empty unit id")
    demo_prefix = "DEMO-"
    unit_prefix = "UNIT-"
    if re.fullmatch(r"\d+", u):
        prefix = demo_prefix if test else unit_prefix
        return f"{prefix}{int(u):04d}"
    m = re.fullmatch(r"(UNIT|DEMO)-(\d+)", u, re.IGNORECASE)
    if m:
        prefix = m.group(1).upper() + "-"
        if test and prefix != demo_prefix:
            pass  # allow UNIT- in test mode if explicitly given
        return f"{prefix}{int(m.group(2)):04d}"
    if not re.fullmatch(r"[A-Za-z0-9._-]+", u):
        raise ValueError(f"asset_id unsafe: {unit!r}")
    return u


def _hw_profile_to_variant(hw_profile: str) -> str:
    prof = (hw_profile or "").strip().upper()
    if prof in _LEGACY_HW_PROFILE_ALIASES:
        return _LEGACY_HW_PROFILE_ALIASES[prof]
    if prof == "FLEXBOX_PLUS":
        return "FLEXBOX_PLUS"
    if prof in ("", "FLEXBOX"):
        return "FLEXBOX"
    raise ValueError(
        f"hw_profile {hw_profile!r} must be FLEXBOX_PLUS, FLEXBOX, or a legacy alias"
    )


def _hex_field_to_bytes(hex_str: str, length: int, name: str) -> bytes:
    h = _normalize_hex_string(hex_str)
    if len(h) != length * 2:
        raise ValueError(f"{name} must be {length * 2} hex chars, got {len(h)}")
    return bytes.fromhex(h)


def _find_registry_row(
    asset_id: str,
    *,
    region: str,
    test: bool,
) -> tuple[Path, dict[str, str]]:
    primary = registry_csv_path(region, test=test)
    row = _find_row_in_csv(primary, asset_id)
    if row is not None:
        return primary, row
    if test:
        raise RuntimeError(f"asset_id {asset_id!r} not found in {primary}")
    for path in master_registry_paths():
        if path.resolve() == primary.resolve():
            continue
        row = _find_row_in_csv(path, asset_id)
        if row is not None:
            print(
                f"NOTE: {asset_id} found in {path.name} "
                f"(preset region is {region})",
                file=sys.stderr,
            )
            return path, row
    raise RuntimeError(f"asset_id {asset_id!r} not found in master registries")


def _find_row_in_csv(path: Path, asset_id: str) -> dict[str, str] | None:
    if not path.exists():
        return None
    want = asset_id.strip().upper()
    for row in _read_existing_registry(path):
        if (row.get("asset_id") or "").strip().upper() == want:
            return row
    return None


def _c_string_literal(s: str) -> str:
    return (s or "").replace("\\", "\\\\").replace('"', '\\"')


def _replace_device_hw_variant(contents: str, variant: str) -> str:
    if variant not in ("FLEXBOX", "FLEXBOX_PLUS"):
        raise ValueError(f"invalid variant {variant!r}")
    ifndef_block = re.compile(
        r"#ifndef DEVICE_HW_VARIANT\s*\n"
        r"#define DEVICE_HW_VARIANT\s+\w+\s*\n"
        r"#endif",
        re.MULTILINE,
    )
    if ifndef_block.search(contents):
        return ifndef_block.sub(f"#define DEVICE_HW_VARIANT {variant}", contents, count=1)
    updated, n = DEVICE_HW_VARIANT_RE.subn(
        f"#define DEVICE_HW_VARIANT {variant}", contents, count=1
    )
    if n != 1:
        raise RuntimeError(f"Could not update DEVICE_HW_VARIANT in {ONBOARDING_CONFIG_H}")
    return updated


def _replace_onboarding_registry_strings(
    contents: str,
    *,
    name_prefix: str,
    tag_client: str,
    decal_type: str,
) -> str:
    replacements = (
        (
            "DEVICE_REGISTRY_NAME_PREFIX_STRING",
            re.compile(
                r"#ifndef DEVICE_REGISTRY_NAME_PREFIX_STRING\s*\n"
                r"#define DEVICE_REGISTRY_NAME_PREFIX_STRING\s+\"[^\"]*\"\s*\n"
                r"#endif",
                re.MULTILINE,
            ),
            name_prefix,
        ),
        (
            "DEVICE_REGISTRY_CLIENT_NAME",
            re.compile(
                r"#ifndef DEVICE_REGISTRY_CLIENT_NAME\s*\n"
                r"#define DEVICE_REGISTRY_CLIENT_NAME\s+\"[^\"]*\"\s*\n"
                r"#endif",
                re.MULTILINE,
            ),
            tag_client,
        ),
        (
            "DEVICE_REGISTRY_DECAL_TYPE",
            re.compile(
                r"#ifndef DEVICE_REGISTRY_DECAL_TYPE\s*\n"
                r"#define DEVICE_REGISTRY_DECAL_TYPE\s+\"[^\"]*\"\s*\n"
                r"#endif",
                re.MULTILINE,
            ),
            decal_type,
        ),
    )
    for macro, pattern, value in replacements:
        block = f'#define {macro} "{_c_string_literal(value)}"'
        if pattern.search(contents):
            contents = pattern.sub(block, contents, count=1)
        else:
            bare = re.compile(rf"#define\s+{macro}\s+\"[^\"]*\"")
            if bare.search(contents):
                contents = bare.sub(block, contents, count=1)
            else:
                raise RuntimeError(f"Missing {macro} in {ONBOARDING_CONFIG_H}")
    return contents


def _parse_onboarding_registry_metadata(
    onboarding_text: str, prj_text: str
) -> dict[str, str]:
    """Registry/AWS tag fields from onboarding_config.h (keys flow direction)."""
    variant = _parse_device_hw_variant(onboarding_text)
    return {
        "variant": variant,
        "hw_profile": _hardware_profile_code(onboarding_text, prj_text),
        "name_prefix": _parse_registry_name_prefix(onboarding_text),
        "tag_client": _parse_registry_client_name(onboarding_text),
        "decal_type": _parse_registry_decal_type(onboarding_text),
    }


def _update_registry_row_metadata(
    csv_path: Path,
    asset_id: str,
    *,
    provision_iso: str,
    fw_ver: str,
    hw_ver: str,
    hw_profile: str,
    name_prefix: str | None = None,
    tag_client: str | None = None,
    decal_type: str | None = None,
) -> None:
    rows = _read_existing_registry(csv_path)
    want = asset_id.strip().upper()
    found = False
    for row in rows:
        if (row.get("asset_id") or "").strip().upper() != want:
            continue
        row["provision_utc"] = provision_iso
        row["fw_version"] = fw_ver
        row["hw_version"] = hw_ver
        row["hw_profile"] = hw_profile
        if name_prefix is not None:
            row["name_prefix"] = name_prefix
        if tag_client is not None:
            row["tag_client"] = tag_client
        if decal_type is not None:
            row["decal_type"] = decal_type
        found = True
        break
    if not found:
        raise RuntimeError(f"asset_id {asset_id!r} not in {csv_path}")
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=REGISTRY_FIELDS, quoting=csv.QUOTE_ALL)
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in REGISTRY_FIELDS})


def sync_unit_from_registry(
    *,
    unit: str,
    profile: BuildProfile,
    test: bool = False,
    dry_run: bool = False,
    from_config: bool = False,
) -> tuple[int, dict[str, str] | None]:
    """
    Fleet re-provision: load existing CSV row into headers, stamp provision time,
    update CSV metadata from sys_config.h, sync build profile. No new keys.

    Default: hw_profile and registry strings come from the CSV row (→ onboarding_config.h).
    With from_config=True: those fields come from onboarding_config.h (→ CSV row).
    """
    try:
        asset_id = normalize_asset_id(unit, test=test)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2, None

    try:
        csv_path, row = _find_registry_row(asset_id, region=profile.region, test=test)
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2, None

    try:
        dev_eui = _hex_field_to_bytes(row["dev_eui"], 8, "dev_eui")
        join_eui = _hex_field_to_bytes(row["join_eui"], 8, "join_eui")
        app_key = _hex_field_to_bytes(row["app_key"], 16, "app_key")
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2, None

    if not EUI_KEYS_H.exists() or not ONBOARDING_CONFIG_H.exists() or not SYS_CONFIG_H.exists():
        print("ERROR: missing app headers (eui_keys.h / onboarding_config.h / sys_config.h)", file=sys.stderr)
        return 2, None
    if from_config and not PRJ_CONF.exists():
        print(f"ERROR: missing {PRJ_CONF}", file=sys.stderr)
        return 2, None

    sc_text = SYS_CONFIG_H.read_text(encoding="utf-8")
    onb_text = ONBOARDING_CONFIG_H.read_text(encoding="utf-8")
    prj_text = PRJ_CONF.read_text(encoding="utf-8") if from_config else ""
    try:
        fw_ver, hw_ver = _parse_fw_hw_versions(sc_text)
        if from_config:
            meta = _parse_onboarding_registry_metadata(onb_text, prj_text)
            variant = meta["variant"]
            hw_profile_code = meta["hw_profile"]
            name_prefix = meta["name_prefix"]
            tag_client = meta["tag_client"]
            decal_type = meta["decal_type"]
        else:
            variant = _hw_profile_to_variant(row.get("hw_profile", ""))
            hw_profile_code = variant if variant == "FLEXBOX_PLUS" else "FLEXBOX"
            name_prefix = (row.get("name_prefix") or "").strip()
            tag_client = (row.get("tag_client") or "").strip()
            decal_type = (
                row.get("decal_type") or row.get("tag_location") or ""
            ).strip()
    except (RuntimeError, ValueError) as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2, None

    prov_now = datetime.now(timezone.utc)
    provision_unix = int(prov_now.timestamp())
    provision_iso = prov_now.strftime("%Y-%m-%dT%H:%M:%SZ")

    print("")
    print("=== Sync unit from registry (no new keys) ===")
    print(f"Asset ID  : {asset_id}")
    print(f"Registry  : {csv_path}")
    print(f"DevEUI    : {_colon_hex(dev_eui)}")
    if from_config:
        print(f"Metadata  : from {ONBOARDING_CONFIG_H.name} → CSV")
    print(f"Variant   : {variant} (hw_profile → {hw_profile_code})")
    if from_config:
        print(f"Tags      : prefix={name_prefix!r}  client={tag_client!r}  decal={decal_type!r}")
    print(f"Build     : {profile.hardware} + {profile.region}")
    print(f"FW/HW     : {fw_ver} / {hw_ver}")
    print(f"Provision : {provision_iso}")
    if dry_run:
        print("(dry run — no header/CSV/build changes)")
        print("")
        return 0, row

    generated_block = (
        f"{BEGIN_MARKER}\n"
        f"/* UNIT_ID: {asset_id} */\n"
        + _fmt_eui_define("LORAWAN_DEV_EUI", dev_eui)
        + "\n"
        + _fmt_eui_define("LORAWAN_JOIN_EUI", join_eui)
        + "\n"
        + _fmt_app_key_define(app_key)
        + f"{END_MARKER}\n"
    )
    eui_text = EUI_KEYS_H.read_text(encoding="utf-8")
    eui_text = _replace_generated_section(eui_text, generated_block)
    _atomic_write(EUI_KEYS_H, eui_text)

    onb_text = _replace_onboarding_unit_id(onb_text, asset_id)
    onb_text = _replace_onboarding_provision_utc(onb_text, provision_unix, provision_iso)
    onb_text = _replace_device_hw_variant(onb_text, variant)
    onb_text = _replace_onboarding_registry_strings(
        onb_text,
        name_prefix=name_prefix,
        tag_client=tag_client,
        decal_type=decal_type,
    )
    _atomic_write(ONBOARDING_CONFIG_H, onb_text)

    _update_registry_row_metadata(
        csv_path,
        asset_id,
        provision_iso=provision_iso,
        fw_ver=fw_ver,
        hw_ver=hw_ver,
        hw_profile=hw_profile_code,
        name_prefix=name_prefix if from_config else None,
        tag_client=tag_client if from_config else None,
        decal_type=decal_type if from_config else None,
    )


    try:
        apply_build_profile(profile)
    except (RuntimeError, ValueError) as e:
        print(f"ERROR: build profile update failed: {e}", file=sys.stderr)
        return 6, None

    print(f"Updated   : {EUI_KEYS_H.name}, {ONBOARDING_CONFIG_H.name}")
    print(f"Updated   : {csv_path} row {asset_id}")
    print(f"Build     : {PRJ_CONF.name} + overlay ({profile.hardware}/{profile.region})")
    print("")
    return 0, row


def stamp_provision_only() -> int:
    if not ONBOARDING_CONFIG_H.exists():
        print(f"ERROR: {ONBOARDING_CONFIG_H} not found", file=sys.stderr)
        return 2
    prov_now = datetime.now(timezone.utc)
    provision_unix = int(prov_now.timestamp())
    provision_iso = prov_now.strftime("%Y-%m-%dT%H:%M:%SZ")
    try:
        onb_text = ONBOARDING_CONFIG_H.read_text(encoding="utf-8")
        onb_text = _replace_onboarding_provision_utc(
            onb_text, provision_unix, provision_iso
        )
        _atomic_write(ONBOARDING_CONFIG_H, onb_text)
    except (RuntimeError, ValueError) as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2
    print("")
    print("=== Provision stamp only (no EUI/key/CSV/prj/overlay changes) ===")
    print(f"DEVICE_PROVISION_UNIX_UTC      = {provision_unix}ULL")
    print(f'DEVICE_PROVISION_ISO8601_UTC    = "{provision_iso}"')
    print(f"Updated: {ONBOARDING_CONFIG_H}")
    print("")
    return 0


def generate_keys(profile: BuildProfile, *, test: bool = False) -> tuple[int, dict | None]:
    """
    Generate keys, update headers, append registry row, sync build profile.
    Returns (exit_code, new_row dict or None on failure).
    """
    registry_csv = registry_csv_path(profile.region, test=test)

    for p in collision_registry_paths(test=test):
        _normalize_registry_csv(p)

    existing_rows = _read_existing_registry(registry_csv)
    all_rows: list[dict[str, str]] = []
    for p in collision_registry_paths(test=test):
        all_rows.extend(_read_existing_registry(p))

    label = "demo_units" if test else "master"
    print(f"Target registry ({label}): {registry_csv} (existing rows: {len(existing_rows)})")
    print(f"Build profile: {profile.hardware} + {profile.region}")
    print(f"Collision check across {len(collision_registry_paths(test=test))} CSV file(s)")

    existing_dev_euis = {_normalize_hex_string(r.get("dev_eui", "")) for r in all_rows}
    existing_join_euis = {_normalize_hex_string(r.get("join_eui", "")) for r in all_rows}
    existing_app_keys = {_normalize_hex_string(r.get("app_key", "")) for r in all_rows}

    for _ in range(100):
        dev_eui = _dev_eui()
        if _plain_hex(dev_eui).upper() not in existing_dev_euis:
            break
    else:
        print("ERROR: failed to generate a unique DevEUI", file=sys.stderr)
        return 3, None

    for _ in range(100):
        join_eui = _eui64_local()
        if _plain_hex(join_eui).upper() not in existing_join_euis:
            break
    else:
        print("ERROR: failed to generate a unique JoinEUI", file=sys.stderr)
        return 4, None

    for _ in range(100):
        app_key = _app_key()
        if _plain_hex(app_key).upper() not in existing_app_keys:
            break
    else:
        print("ERROR: failed to generate a unique AppKey", file=sys.stderr)
        return 5, None

    asset_id = _next_asset_id(existing_rows, prefix="DEMO-" if test else "UNIT-")

    if not EUI_KEYS_H.exists() or not ONBOARDING_CONFIG_H.exists() or not SYS_CONFIG_H.exists():
        print("ERROR: missing app headers (eui_keys.h / onboarding_config.h / sys_config.h)", file=sys.stderr)
        return 2, None

    onb_text = ONBOARDING_CONFIG_H.read_text(encoding="utf-8")
    sc_text = SYS_CONFIG_H.read_text(encoding="utf-8")
    prj_text = PRJ_CONF.read_text(encoding="utf-8")
    fw_ver, hw_ver = _parse_fw_hw_versions(sc_text)
    hw_profile = _hardware_profile_code(onb_text, prj_text)

    prov_now = datetime.now(timezone.utc)
    provision_unix = int(prov_now.timestamp())
    provision_iso = prov_now.strftime("%Y-%m-%dT%H:%M:%SZ")

    name_prefix_csv = _parse_registry_name_prefix(onb_text)
    tag_client_csv = _parse_registry_client_name(onb_text)
    decal_type_csv = _parse_registry_decal_type(onb_text)

    contents = EUI_KEYS_H.read_text(encoding="utf-8")
    generated_block = (
        f"{BEGIN_MARKER}\n"
        f"/* UNIT_ID: {asset_id} */\n"
        + _fmt_eui_define("LORAWAN_DEV_EUI", dev_eui)
        + "\n"
        + _fmt_eui_define("LORAWAN_JOIN_EUI", join_eui)
        + "\n"
        + _fmt_app_key_define(app_key)
        + f"{END_MARKER}\n"
    )
    contents = _replace_generated_section(contents, generated_block)
    _atomic_write(EUI_KEYS_H, contents)

    onb_text = _replace_onboarding_unit_id(onb_text, asset_id)
    onb_text = _replace_onboarding_provision_utc(onb_text, provision_unix, provision_iso)
    _atomic_write(ONBOARDING_CONFIG_H, onb_text)

    new_row = {
        "asset_id": asset_id,
        "dev_eui": _plain_hex(dev_eui),
        "join_eui": _plain_hex(join_eui),
        "app_key": _plain_hex(app_key),
        "provision_utc": provision_iso,
        "fw_version": fw_ver,
        "hw_version": hw_ver,
        "hw_profile": hw_profile,
        "name_prefix": name_prefix_csv,
        "tag_client": tag_client_csv,
        "decal_type": decal_type_csv,
    }

    registry_csv.parent.mkdir(parents=True, exist_ok=True)
    write_header = (not registry_csv.exists()) or registry_csv.stat().st_size == 0
    with registry_csv.open("a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=REGISTRY_FIELDS, quoting=csv.QUOTE_ALL)
        if write_header:
            writer.writeheader()
        writer.writerow(new_row)

    try:
        apply_build_profile(profile)
    except (RuntimeError, ValueError) as e:
        print(f"ERROR: build profile update failed: {e}", file=sys.stderr)
        return 6, None

    print("")
    print("=== Provisioned credentials ===")
    print(f"Mode     : {'TEST (demo_units)' if test else 'production registry'}")
    print(f"Asset ID : {asset_id}")
    print(f"DevEUI   : {_colon_hex(dev_eui)}")
    print(f"JoinEUI  : {_colon_hex(join_eui)}")
    print(f"Registry : {registry_csv}")
    print(f"Build    : {PRJ_CONF.name} + overlay ({profile.hardware}/{profile.region})")
    print("")
    return 0, new_row


def run_legacy_gen_euis_main(argv: list[str] | None = None) -> int:
    """Backward-compatible gen_euis.py entry point."""
    parser = argparse.ArgumentParser(
        description="[deprecated — use provision.py] Generate LoRaWAN EUIs/keys."
    )
    parser.add_argument("--region", choices=("us915", "eu868"), default=None)
    parser.add_argument("--EU", action="store_true")
    parser.add_argument("--sync-build-only", action="store_true")
    parser.add_argument("--stamp-provision-only", action="store_true")
    parser.add_argument(
        "--test",
        action="store_true",
        help="Write registry under flexbox_euis/demo_units/",
    )
    args = parser.parse_args(argv)

    print("NOTE: gen_euis.py is deprecated; use: python onboarding/provision.py ...", file=sys.stderr)

    if args.sync_build_only and args.stamp_provision_only:
        print("ERROR: use either --sync-build-only or --stamp-provision-only", file=sys.stderr)
        return 2
    if args.stamp_provision_only:
        return stamp_provision_only()

    region = "eu868" if args.EU else (args.region or "us915").lower()
    hardware = "seeed" if region == "eu868" else "lr62"
    try:
        profile = BuildProfile(hardware=hardware, region=region)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    if args.sync_build_only:
        try:
            apply_build_profile(profile)
        except (RuntimeError, ValueError) as e:
            print(f"ERROR: {e}", file=sys.stderr)
            return 2
        print(f"Build profile synced: {profile.hardware} + {profile.region}")
        return 0

    code, _ = generate_keys(profile, test=args.test)
    return code


# --- helpers (unchanged logic from gen_euis.py) ---


def _parse_fw_hw_versions(sys_config_text: str) -> tuple[str, str]:
    fm = FW_VERSION_STRING_RE.search(sys_config_text)
    hm = HW_VERSION_STRING_RE.search(sys_config_text)
    if not fm or not hm:
        raise RuntimeError(f"Could not parse FW/HW version in {SYS_CONFIG_H}")
    return fm.group(1).strip(), hm.group(1).strip()


def _parse_device_hw_variant(onboarding_text: str) -> str:
    m = DEVICE_HW_VARIANT_RE.search(onboarding_text)
    if not m:
        raise RuntimeError(f"Could not parse DEVICE_HW_VARIANT in {ONBOARDING_CONFIG_H}")
    return m.group(1)


def validate_hw_variant_build() -> list[str]:
    """
    Check DEVICE_HW_VARIANT matches prj fragments, base overlay, and plus overlay.
    Returns human-readable ERROR:/WARNING: strings (empty if OK).
    """
    issues: list[str] = []
    onboarding_text = ONBOARDING_CONFIG_H.read_text(encoding="utf-8")
    variant = _parse_device_hw_variant(onboarding_text)
    prj_base = PRJ_CONF.read_text(encoding="utf-8")
    overlay_base = BOARD_OVERLAY.read_text(encoding="utf-8")

    enabled_in_base = {
        "PN5180": CONFIG_PN5180_Y_RE.search(prj_base),
        "SSD1683": CONFIG_SSD1683_Y_RE.search(prj_base),
        "DISPLAY": CONFIG_DISPLAY_Y_RE.search(prj_base),
        "LVGL": CONFIG_LVGL_Y_RE.search(prj_base),
    }
    for name, enabled in enabled_in_base.items():
        if enabled:
            issues.append(
                f"ERROR: {name} enabled in prj.conf; use prj_flexbox*.conf fragments only"
            )

    if SSD1683_DT_RE.search(overlay_base) or PN5180_DT_RE.search(overlay_base):
        issues.append(
            "ERROR: base overlay contains EPD/NFC nodes; use flexbox_plus overlay only"
        )

    if variant == "FLEXBOX":
        if not PRJ_FLEXBOX_CONF.exists():
            issues.append(f"ERROR: missing {PRJ_FLEXBOX_CONF.name}")
        if FLEXBOX_PLUS_OVERLAY.exists():
            plus_ovl = FLEXBOX_PLUS_OVERLAY.read_text(encoding="utf-8")
            if SSD1683_DT_RE.search(plus_ovl) or PN5180_DT_RE.search(plus_ovl):
                pass  # plus overlay is inert unless CMake selects it
    else:
        if not PRJ_FLEXBOX_PLUS_CONF.exists():
            issues.append(f"ERROR: missing {PRJ_FLEXBOX_PLUS_CONF.name}")
        else:
            plus_conf = PRJ_FLEXBOX_PLUS_CONF.read_text(encoding="utf-8")
            for name, regex in (
                ("PN5180", CONFIG_PN5180_Y_RE),
                ("SSD1683", CONFIG_SSD1683_Y_RE),
                ("DISPLAY", CONFIG_DISPLAY_Y_RE),
                ("LVGL", CONFIG_LVGL_Y_RE),
            ):
                if not regex.search(plus_conf):
                    issues.append(
                        f"ERROR: FLEXBOX_PLUS but {name} not enabled in "
                        f"{PRJ_FLEXBOX_PLUS_CONF.name}"
                    )
        if not FLEXBOX_PLUS_OVERLAY.exists():
            issues.append(f"ERROR: missing {FLEXBOX_PLUS_OVERLAY.name}")
        else:
            plus_ovl = FLEXBOX_PLUS_OVERLAY.read_text(encoding="utf-8")
            if not SSD1683_DT_RE.search(plus_ovl):
                issues.append(
                    f"ERROR: FLEXBOX_PLUS but no ssd1683 node in {FLEXBOX_PLUS_OVERLAY.name}"
                )
            if not PN5180_DT_RE.search(plus_ovl):
                issues.append(
                    f"ERROR: FLEXBOX_PLUS but no pn5180 node in {FLEXBOX_PLUS_OVERLAY.name}"
                )

    return issues


def _hardware_profile_code(onboarding_text: str, prj_text: str) -> str:
    del prj_text  # build fragments are validated separately
    variant = _parse_device_hw_variant(onboarding_text)
    if variant != "FLEXBOX_PLUS":
        return "FLEXBOX"
    if not PRJ_FLEXBOX_PLUS_CONF.exists():
        print(
            f"WARNING: missing {PRJ_FLEXBOX_PLUS_CONF.name} — registry hw_profile FLEXBOX",
            file=sys.stderr,
        )
        return "FLEXBOX"
    plus_conf = PRJ_FLEXBOX_PLUS_CONF.read_text(encoding="utf-8")
    if not CONFIG_PN5180_Y_RE.search(plus_conf):
        print(
            "WARNING: DEVICE_HW_VARIANT FLEXBOX_PLUS but CONFIG_PN5180 is not "
            f"enabled in {PRJ_FLEXBOX_PLUS_CONF.name} — registry hw_profile FLEXBOX",
            file=sys.stderr,
        )
        return "FLEXBOX"
    return "FLEXBOX_PLUS"


def _parse_registry_name_prefix(onboarding_text: str) -> str:
    m = REGISTRY_NAME_PREFIX_STRING_RE.search(onboarding_text)
    if not m:
        return ""
    s = m.group(1).strip()
    if s and not re.fullmatch(r"[A-Za-z0-9._-]+", s):
        raise RuntimeError(f"Invalid DEVICE_REGISTRY_NAME_PREFIX_STRING: {s!r}")
    return s


def _parse_registry_client_name(onboarding_text: str) -> str:
    m = REGISTRY_CLIENT_NAME_RE.search(onboarding_text)
    return m.group(1).strip() if m else ""


def _parse_registry_decal_type(onboarding_text: str) -> str:
    m = REGISTRY_DECAL_TYPE_RE.search(onboarding_text)
    return m.group(1).strip() if m else ""


def _registry_row_value(row: dict[str, str], new_key: str, legacy_key: str | None = None) -> str:
    v = (row.get(new_key) or "").strip()
    if v or not legacy_key:
        return v
    return (row.get(legacy_key) or "").strip()


def _fmt_c_array_hex(bytes_: bytes) -> str:
    return ", ".join(f"0x{b:02x}" for b in bytes_)


def _fmt_eui_define(name: str, eui: bytes) -> str:
    if len(eui) != 8:
        raise ValueError("EUI must be 8 bytes")
    return (
        f"#define {name}                                                        \\\n"
        f"  {{ {_fmt_c_array_hex(eui)} }}\n"
    )


def _fmt_app_key_define(app_key: bytes) -> str:
    if len(app_key) != 16:
        raise ValueError("AppKey must be 16 bytes")
    first = _fmt_c_array_hex(app_key[:12])
    last = _fmt_c_array_hex(app_key[12:])
    return (
        "#define LORAWAN_APP_KEY                                                        \\\n"
        "  {                                                                            \\\n"
        f"    {first},    \\\n"
        f"        {last}                                                 \\\n"
        "  }\n"
    )


def _eui64_local() -> bytes:
    b = bytearray(secrets.token_bytes(8))
    b[0] = (b[0] | 0x02) & 0xFE
    return bytes(b)


def _dev_eui() -> bytes:
    suffix = secrets.token_bytes(8 - len(DEV_EUI_PREFIX))
    b = bytearray(DEV_EUI_PREFIX + suffix)
    b[0] = (b[0] | 0x02) & 0xFE
    return bytes(b)


def _app_key() -> bytes:
    return secrets.token_bytes(16)


def _colon_hex(bytes_: bytes) -> str:
    return ":".join(f"{b:02X}" for b in bytes_)


def _plain_hex(bytes_: bytes) -> str:
    return "".join(f"{b:02X}" for b in bytes_)


def _normalize_hex_string(s: str) -> str:
    return re.sub(r"[^0-9A-Fa-f]", "", (s or "")).upper()


def _read_existing_registry(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _next_asset_id(existing_rows: Iterable[dict[str, str]], *, prefix: str = "UNIT-") -> str:
    max_n = 0
    for r in existing_rows:
        aid = (r.get("asset_id") or "").strip()
        if not aid.startswith(prefix):
            continue
        suffix = aid[len(prefix) :]
        if suffix.isdigit():
            max_n = max(max_n, int(suffix))
    return f"{prefix}{max_n + 1:04d}"


def _replace_between_markers(
    contents: str, begin_marker: str, end_marker: str, new_inner: str
) -> str:
    bi = contents.find(begin_marker)
    if bi < 0:
        raise RuntimeError(f"Missing begin marker {begin_marker!r}")
    line_end = contents.find("\n", bi)
    if line_end < 0:
        raise RuntimeError(f"Begin marker line has no newline: {begin_marker!r}")
    start_inner = line_end + 1
    ei = contents.find(end_marker, start_inner)
    if ei < 0:
        raise RuntimeError(f"Missing end marker {end_marker!r}")
    return contents[:start_inner] + new_inner + contents[ei:]


def _replace_onboarding_unit_id(contents: str, asset_id: str) -> str:
    if UNIT_ID_SYS_BEGIN not in contents or UNIT_ID_SYS_END not in contents:
        raise RuntimeError(f"Missing unit-id markers in {ONBOARDING_CONFIG_H}")
    if not re.fullmatch(r"[A-Za-z0-9._-]+", asset_id or ""):
        raise ValueError(f"asset_id unsafe for C string: {asset_id!r}")
    start = contents.index(UNIT_ID_SYS_BEGIN)
    end_idx = contents.index(UNIT_ID_SYS_END)
    end_line = contents.find("\n", end_idx)
    if end_line == -1:
        end_line = len(contents)
    block = (
        f"{UNIT_ID_SYS_BEGIN}\n"
        f'#define DEVICE_UNIT_ID_STRING "{asset_id}"\n'
        f"{UNIT_ID_SYS_END}\n"
    )
    return contents[:start] + block + contents[end_line + 1 :]


def _replace_onboarding_provision_utc(
    contents: str, unix_ts: int, iso8601_z: str
) -> str:
    if PROVISION_UTC_BEGIN not in contents or PROVISION_UTC_END not in contents:
        raise RuntimeError(f"Missing PROVISION_UTC markers in {ONBOARDING_CONFIG_H}")
    if not PROVISION_ISO_RE.fullmatch(iso8601_z):
        raise ValueError(f"iso8601_z must match ...Z format, got {iso8601_z!r}")
    start = contents.index(PROVISION_UTC_BEGIN)
    end_idx = contents.index(PROVISION_UTC_END)
    end_line = contents.find("\n", end_idx)
    if end_line == -1:
        end_line = len(contents)
    block = (
        f"{PROVISION_UTC_BEGIN}\n"
        f"#define DEVICE_PROVISION_UNIX_UTC {unix_ts}ULL\n"
        f'#define DEVICE_PROVISION_ISO8601_UTC "{iso8601_z}"\n'
        f"{PROVISION_UTC_END}\n"
    )
    return contents[:start] + block + contents[end_line + 1 :]


def _replace_generated_section(contents: str, generated_block: str) -> str:
    if BEGIN_MARKER not in contents or END_MARKER not in contents:
        raise RuntimeError(f"Missing generated markers in {EUI_KEYS_H}")
    start = contents.index(BEGIN_MARKER)
    end = contents.index(END_MARKER)
    end_line = contents.find("\n", end)
    if end_line == -1:
        end_line = len(contents)
    return contents[:start] + generated_block + contents[end_line + 1 :]


def _normalize_registry_csv(path: Path) -> None:
    if not path.exists() or path.stat().st_size == 0:
        return
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        if not fieldnames:
            return
        if not {"asset_id", "dev_eui", "join_eui", "app_key"} <= set(fieldnames):
            return
        rows = list(reader)
    if tuple(fieldnames) == tuple(REGISTRY_FIELDS):
        return
    tmp = path.with_suffix(".csv.tmp")
    with tmp.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=REGISTRY_FIELDS, quoting=csv.QUOTE_ALL)
        writer.writeheader()
        for r in rows:
            out = {
                k: _registry_row_value(
                    r, k, legacy_key="tag_location" if k == "decal_type" else None
                )
                for k in REGISTRY_FIELDS
            }
            writer.writerow(out)
    tmp.replace(path)


def _atomic_write(path: Path, text: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)
