CONFIG_DISK_ACCESS=y
CONFIG_LOG=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=2048


# CONFIG_LOG_DEFAULT_LEVEL=4
# CONFIG_SPI_LOG_LEVEL_DBG=y
# CONFIG_DISK_LOG_LEVEL_DBG=y
# CONFIG_SDHC_LOG_LEVEL_DBG=y
